# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Josh Clark
tagline:          'Research, Methods, Data'
description:      'Teaching resources and research about virtual worlds, social network analysis and open data'
url:              joshuaaclark.github.io
baseurl:          joshuaaclark.github.io

author:
  name:           'Joshua Clark'
  url:            https://twitter.com/joshuaaclark

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/joshuaaclark/
